### ISSUE TITLE
not able to build qspif- blockdevice

### ISSUE THREAD

**Issue by nagarathna321** [ARMmbed/qspif-blockdevice#21] opened 2019-07-17 05:42 UTC
Hi , I am new to mbed tool  ,I have started working on nor flash with the psoc 6 when I am trying to compile the code i am getting error as bellow shown 

[Error] QSPIFBlockDevice.h@229,5: 'qspi_status_t' does not name a type; did you mean 'nsapi_stack_t'?
[Error] QSPIFBlockDevice.h@233,5: 'qspi_status_t' does not name a type; did you mean 'nsapi_stack_t'?
[Error] QSPIFBlockDevice.h@236,5: 'qspi_status_t' does not name a type; did you mean 'nsapi_stack_t'?
[Error] QSPIFBlockDevice.h@239,5: 'qspi_status_t' does not name a type; did you mean 'nsapi_stack_t'?
[Error] QSPIFBlockDevice.h@243,5: 'qspi_status_t' does not name a type; did you mean 'nsapi_stack_t'?
[Error] QSPIFBlockDevice.h@248,5: 'qspi_status_t' does not name a type; did you mean 'nsapi_stack_t'?
[Error] QSPIFBlockDevice.h@310,11: 'QSPI' in namespace 'mbed' does not name a type

 
I have added all related eader file sitll i am not getting please help me out .

thanks

**Comment by ciarmcom** [comment] 2019-07-17 13:30
ARM Internal Ref: IOTSTOR-886

**Comment by michalpasztamobica** [comment] 2019-08-12 09:25
Hi, @nagarathna321 . `QSPIF` lives under the `components` directory in mbed-os, os you might need to add the following line to your mbed_app.json, to get it working:
```
{
    "target_overrides": {
        "*": {
            "target.components_add": ["QSPIF"],
        }
    }
}

```
Have you tried this already?
If you did and you still have issues, the please, paste the exact command you are using to build the code and the contents of your mbed-app.json.

**Comment by michalpasztamobica** [comment] 2019-08-27 08:54
It seems that the problem is related to environment configuration, but we have no response from the reporter. I suggest we close the issue.

**Comment by rblaze** [comment] 2019-12-02 03:56
Hello,

I run into the same issue. Here is relevant information:
```
blaze@andrey-XPS:~/dev/mbed/flash_writer$ mbed target
[mbed] Working path "/home/blaze/dev/mbed/flash_writer" (program)
[mbed] NUCLEO_F446ZE
blaze@andrey-XPS:~/dev/mbed/flash_writer$ mbed toolchain
[mbed] Working path "/home/blaze/dev/mbed/flash_writer" (program)
[mbed] GCC_ARM
blaze@andrey-XPS:~/dev/mbed/flash_writer$ cat mbed_app.json 
{
    "target_overrides": {
        "*": {
            "target.components_add": ["QSPIF"]
        },
        "K64F": {
            "platform.stdio-baud-rate": 9600
        }
    }
}
blaze@andrey-XPS:~/dev/mbed/flash_writer$ cat main.cpp 
#include "mbed.h"
#include "QSPI.h"
//#include "QSPIFBlockDevice.h"

int main() {
//  QSPIFBlockDevice sdd(PD_11, PD_12, PE_2, PD_13, PB_2, PB_6);

  for (;;) {
  }
}
```

When I'm running `mbed compile`, I'm getting multiple errors:
```
blaze@andrey-XPS:~/dev/mbed/flash_writer$ mbed compile
[mbed] Working path "/home/blaze/dev/mbed/flash_writer" (program)
[Warning] @,: Compiler version mismatch: Have 8.3.1; expected version >= 6.0.0 and < 7.0.0
Building project flash_writer (NUCLEO_F446ZE, GCC_ARM)
Scan: flash_writer
Compile [  6.0%]: USBCDC.cpp
Compile [  6.1%]: USBCDC_ECM.cpp
[...]
Compile [ 12.3%]: QSPIFBlockDevice.cpp
[Error] QSPIFBlockDevice.h@238,5: 'qspi_status_t' does not name a type
[Error] QSPIFBlockDevice.h@242,5: 'qspi_status_t' does not name a type
[Error] QSPIFBlockDevice.h@245,5: 'qspi_status_t' does not name a type
[Error] QSPIFBlockDevice.h@248,5: 'qspi_status_t' does not name a type
[Error] QSPIFBlockDevice.h@252,5: 'qspi_status_t' does not name a type
[Error] QSPIFBlockDevice.h@255,5: 'qspi_status_t' does not name a type
[Error] QSPIFBlockDevice.h@258,5: 'qspi_status_t' does not name a type
[Error] QSPIFBlockDevice.h@261,5: 'qspi_status_t' does not name a type
[Error] QSPIFBlockDevice.h@264,5: 'qspi_status_t' does not name a type
[Error] QSPIFBlockDevice.h@336,11: 'QSPI' in namespace 'mbed' does not name a type
[Error] QSPIFBlockDevice.h@341,12: 'SingletonPtr' does not name a type
[Error] QSPIFBlockDevice.h@350,5: 'PlatformMutex' does not name a type
[Error] QSPIFBlockDevice.h@353,11: 'qspi_inst_t' in namespace 'mbed' does not name a type
[Error] QSPIFBlockDevice.h@354,11: 'qspi_inst_t' in namespace 'mbed' does not name a type
[Error] QSPIFBlockDevice.h@358,11: 'qspi_inst_t' in namespace 'mbed' does not name a type
[Error] QSPIFBlockDevice.h@359,11: 'qspi_inst_t' in namespace 'mbed' does not name a type
[Error] QSPIFBlockDevice.h@364,11: 'qspi_inst_t' in namespace 'mbed' does not name a type
[Error] QSPIFBlockDevice.h@367,11: 'qspi_inst_t' in namespace 'mbed' does not name a type
[Error] QSPIFBlockDevice.h@392,5: 'qspi_bus_width_t' does not name a type
[Error] QSPIFBlockDevice.h@393,5: 'qspi_bus_width_t' does not name a type
```

and many more similar lines.

**Comment by michalpasztamobica** [comment] 2019-12-02 10:04
Hi @rblaze .
Seems like the `NUCLEO_F446ZE` target [is indeed missing the QSPI feature](https://github.com/ARMmbed/mbed-os/blob/24c6c4cab56a9e4204808d093e26be73da372463/targets/targets.json#L2979) config.
But even when this is added the pins for QSPIF are not set in [PinNames.h](https://github.com/ARMmbed/mbed-os/blob/master/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446ZE/PinNames.h)

So, it seems this target is not yet supported in mbed-os, even though I can see it has QSPIF support.
You may try to add it yourself, following how other devices has it, for example `DISCO_F413ZH`. If you succeed a PR to mbed-os would be very welcome 😃 

@ARMmbed/mbed-os-storage , @SeppoTakalo  do we need this repository, if QSPIF is in `components` in mbed-os? Should this repository be deprecated?

**Comment by SeppoTakalo** [comment] 2019-12-02 10:24
This repository is deprecated as the QSPIF driver is already in Mbed OS.

**Comment by wind8744** [comment] 2019-12-03 02:16
I'm having the same problem.  
[Error] QSPIFBlockDevice.h@238,5: unknown type name 'qspi_status_t'
[Error] QSPIFBlockDevice.h@242,5: unknown type name 'qspi_status_t'
[Error] QSPIFBlockDevice.h@245,5: unknown type name 'qspi_status_t'
[Error] QSPIFBlockDevice.h@248,5: unknown type name 'qspi_status_t'
[Error] QSPIFBlockDevice.h@252,5: unknown type name 'qspi_status_t'
[Error] QSPIFBlockDevice.h@252,42: unknown type name 'qspi_bus_width_t'
[Error] QSPIFBlockDevice.h@252,71: unknown type name 'qspi_bus_width_t'
[Error] QSPIFBlockDevice.h@253,42: unknown type name 'qspi_address_size_t'
[Error] QSPIFBlockDevice.h@253,76: unknown type name 'qspi_bus_width_t'
[Error] QSPIFBlockDevice.h@253,104: unknown type name 'qspi_alt_size_t'
[Error] QSPIFBlockDevice.h@253,130: unknown type name 'qspi_bus_width_t'
[Error] QSPIFBlockDevice.h@257,5: unknown type name 'qspi_status_t'
[Error] QSPIFBlockDevice.h@317,11: no type named 'QSPI' in namespace 'mbed'; did you mean 'SPI'?
[Error] QSPIFBlockDevice.h@358,5: unknown type name 'qspi_bus_width_t'
[Error] QSPIFBlockDevice.h@359,5: unknown type name 'qspi_bus_width_t'
[Error] QSPIFBlockDevice.h@360,5: unknown type name 'qspi_address_size_t'
[Error] QSPIFBlockDevice.h@361,5: unknown type name 'qspi_bus_width_t'
[Error] QSPIFBlockDevice.h@104,49: use of undeclared identifier 'MBED_CONF_QSPIF_QSPI_FREQ'
[ERROR] In file included from .\main.cpp:1033:

**Comment by 0xc0170** [comment] 2019-12-04 13:08
I'll close the issue as QSPIF driver should be used instead.

**Closed as completed by 0xc0170** 2019-12-04 13:08 UTC
Labels: mirrored, closed_in_jira

**Comment by horeich** [comment] 2020-01-08 11:03
Same error here as @nagarathna321 as soon as I add QSPIFBlockDevice.h to my script.

* MBED 5.14.2
* added support for STM32L476RG, added PinMapping etc.

same error when I add
`"target.components_add": ["QSPIF"]` to target_overrides, as it then is included in kv_store.cpp which fails.

In my main I include
`#include "components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.h"`

`#include <QSPIFBlockDevice.h>` does not work.

**Comment by 0xc0170** [comment] 2020-01-08 15:03
> STM32L476RG

Do you have DEVICE_QSPI enabled and supported?
